/*
 * This file was generated by a tool.
 * Rerun sql-ts to regenerate this file.
 */
export interface AppUser {
  avgDailyCalorieGoal?: number | null;
  awsCognitoSub: string;
  bodyweightGoal?: number | null;
  creationDate: Date;
  email: string;
  emailVerified?: boolean;
  firstName?: string | null;
  id?: number | null;
  imageUrl?: string | null;
  lastName?: string | null;
  lastSignedIn: Date;
  userName?: string | null;
}
export interface CardioSet {
  exerciseSetId: string;
  id?: number | null;
  targetDistance?: number | null;
  targetSpeed?: number | null;
  targetTime?: number | null;
}
export interface CardioSetSession {
  actualDistance?: number | null;
  actualSpeed?: number | null;
  actualTime?: number | null;
  id?: number | null;
  setSessionId: string;
  targetDistance?: number | null;
  targetSpeed?: number | null;
  targetTime?: number | null;
}
export interface CustomCategoryPr {
  customCategoryPrId: string;
  id?: number | null;
  prHistoryId: string;
}
export interface CustomExerciseCategory {
  appUserId: string;
  id?: number | null;
  title: string;
}
export interface DaysOfWeek {
  day: string;
}
export interface Exercise {
  customExerciseCategoryId?: string | null;
  exerciseEquipmentId?: string | null;
  exerciseTypeId: string;
  id?: number | null;
  initialWeight?: number | null;
  listOrder: number;
  notes?: string | null;
  standardExerciseCategoryId?: string | null;
  title: string;
  workoutId: string;
}
export interface ExerciseEquipment {
  id?: number | null;
  title: string;
}
export interface ExerciseSession {
  exerciseTypeId: string;
  id?: number | null;
  initialWeight?: number | null;
  listOrder: number;
  prHistoryId?: string | null;
  title: string;
  wasCompleted?: boolean;
  workoutSessionId: string;
}
export interface ExerciseSet {
  exerciseId: string;
  id?: number | null;
  listOrder: number;
  reps?: number;
  restTime?: number;
  title?: string | null;
}
export interface ExerciseType {
  id?: number | null;
  title: string;
}
export interface LinkTagWorkout {
  id?: number | null;
  workoutId: string;
  workoutTagId: string;
}
export interface PrHistory {
  date: Date;
  distance?: number | null;
  id?: number | null;
  reps?: number | null;
  speed?: number | null;
  time?: number | null;
  weight?: number | null;
}
export interface ResistanceSet {
  exerciseSetId: string;
  id?: number | null;
  totalWeight?: number | null;
}
export interface ResistanceSetSession {
  id?: number | null;
  setSessionId: string;
  totalWeight?: number | null;
}
export interface SetSession {
  elapsedTime?: number;
  exerciseSessionId: string;
  id?: number | null;
  listOrder: number;
  reps?: number;
  restTime?: number;
  title?: string | null;
}
export interface StandardCategoryPr {
  id?: number | null;
  prHistoryId: string;
  standardCategoryPrId: string;
}
export interface StandardExerciseCategory {
  id?: number | null;
  title: string;
}
export interface TrainingCycle {
  appUserId: string;
  id?: number | null;
  listOrder: number;
  title: string;
}
export interface TrainingDay {
  id?: number | null;
  listOrder: number;
  trainingCycleId: string;
}
export interface UserBodyweight {
  appUserId: string;
  date: Date;
  id?: number | null;
  weight: number;
}
export interface Workout {
  appUserId: string;
  id?: number | null;
  lastSession?: Date | null;
  listOrder: number;
  title: string;
  trainingDayId?: string | null;
}
export interface WorkoutDays {
  day: any;
  id?: number | null;
  workoutId?: string | null;
}
export interface WorkoutSession {
  appUserId: string;
  calories?: number | null;
  date: Date;
  id?: number | null;
  tiedToWorkout?: boolean;
  title: string;
}
export interface WorkoutTag {
  appUserId: string;
  id?: number | null;
  title: string;
}
